김유연 week 3 미션 풀이
=============

#### 넘파이 numpy import

In [87]:
import numpy as np

#### Q1. 본격적으로 Numpy와 친해지기 위해서 다양한 연산을 연습해볼 예정입니다. <span style="color: #008000"> **무작위의 데이터를 가 진 5x3의 행렬을 가지는 numpy array와 3x2 행렬을 가지는 numpy array를 만든 후 행열곱 연산**</span>을 진행해보세요.

In [88]:
arr1 = np.random.rand(5,3)
arr2 = np.random.rand(3,2)

In [89]:
dot = arr1@arr2

In [90]:
print(dot, dot.shape)

[[0.99177295 2.12064495]
 [0.74415604 1.76642001]
 [0.46592662 1.34523775]
 [0.26999166 0.85875107]
 [0.18499321 0.42938051]] (5, 2)


#### Q2. 두번째로는 numpy에서 자주 사용하는 concatenate 연산에 대한 미션을 수행해보겠습니다. 이제 Numpy에서 사용하는 2개의 numpy array가 있을때, <span style="color: #008000">**두 numpy array의 concatenate 연산**</span>을 구해보세요.

* axis는 0, 1 두개로 연산한 결과를 출력해보세요.
* 각 데이터가 어떤 형태로 더해지는지 확인해보세요.

In [91]:
arr1 = np.array([[5, 7], [9, 11]], float)
arr2 = np.array([[2, 4], [6, 8]], float)

concat_1 = np.concatenate((arr1, arr2), axis=0) # axis 0
concat_2 = np.concatenate((arr1, arr2), axis=1) # axis 1

In [92]:
print(concat_1)
print(concat_2)

[[ 5.  7.]
 [ 9. 11.]
 [ 2.  4.]
 [ 6.  8.]]
[[ 5.  7.  2.  4.]
 [ 9. 11.  6.  8.]]


#### Q3. 3번부터 5번까지의 미션는 Numpy를 이용해서 정답값을 예측해보는 linear regression을 구현해 보는 미션입니다. 첫번째 단계로 데이터를 준비해보도록 하겠습니다. 아래와 같이 데이터가 주어져있을 때, <span style="color: #008000">**경사하강법을 위한 데이터를 분리**</span>해보세요.

In [93]:
xy = np.array([[1., 2., 3., 4., 5., 6.],
               [10., 20., 30., 40., 50., 60.]])

x_train, y_train = xy

In [94]:
print(x_train, x_train.shape)
print(y_train, y_train.shape)

[1. 2. 3. 4. 5. 6.] (6,)
[10. 20. 30. 40. 50. 60.] (6,)


#### Q4. <span style="color: #008000">**경사 하강법 구현을 위해서 위에서 분리한 x_train 데이터와 계산될 weight, bias 값을 정의해보세요.**</span> 여기서 구현한 weight와 bias 는 linear regression 계산을 진행할시 직선의 기울기와 y 절편의 값이 됩니다.
* numpy내의 random 함수를 이용해보세요.

In [95]:
beta_gd = np.random.rand(1)
bias = np.random.rand(1)

In [96]:
print(beta_gd, bias)

[0.96679813] [0.07623272]


#### Q5. 이제 최종적으로 <span style="color: #008000">**linear regression을 경사하강법으로 학습하는 코드를 구현**</span>해봅시다. 경사하강법 구현을 위한 학습 Loop를 구현해보세요. 최종적으로 1000회 반복했을 시에 결과를 출력하세요.
* 단, Error는 차이의 제곱을 이용해서 계산해주세요.
* Gradient 값은 우리가 예측하는 각 변수에 대한 미분값입니다.

In [97]:
learning_rate = 0.01

# beta_gd, bias 초기화
beta_gd = np.random.rand(1)
bias = np.random.rand(1)

X = np.array([np.append(x, [1]) for x in x_train]) # 상수항 추가

for i in range(1000):
    error = y_train.reshape(6,1) - X @ [beta_gd, bias] # 제곱 하는 방법 찾기
    grad =  - np.transpose(X) @ error
    beta_gd -= learning_rate * grad[0]
    bias -= learning_rate * grad[1]

    if i % 100 == 0:
        print("beta_gd", beta_gd, "bias", bias)
        # print('Epoch ({:10d}/1000) error: {:10f}, beta_gd: {:10f}, bias: {:10f}'.format(i, error, beta_gd.item(), bias.item()))# 오류??

beta_gd [8.91428047] bias [2.95700129]
beta_gd [9.76349031] bias [1.01254492]
beta_gd [9.92134114] bias [0.3367542]
beta_gd [9.97383948] bias [0.11199838]
beta_gd [9.99129948] bias [0.03724864]
beta_gd [9.99710636] bias [0.01238823]
beta_gd [9.99903763] bias [0.0041201]
beta_gd [9.99967993] bias [0.00137027]
beta_gd [9.99989355] bias [0.00045573]
beta_gd [9.9999646] bias [0.00015157]
