In [1]:
# 두 numpy array의 concatenate 연산

In [2]:
import numpy as np

In [3]:
arr1 = np.array([[5, 7], [9, 11]], float)
arr2 = np.array([[2, 4], [6, 8]], float)

In [4]:
concat_1 = np.concatenate((arr1, arr2), axis=0)
concat_2 = np.concatenate((arr1, arr2), axis=1)

In [5]:
print(concat_1)
print(concat_2)

[[ 5.  7.]
 [ 9. 11.]
 [ 2.  4.]
 [ 6.  8.]]
[[ 5.  7.  2.  4.]
 [ 9. 11.  6.  8.]]


In [6]:
#강의 교안에 나와 있던 vstack과 hstack도 활용해 보았습니다

print(np.vstack((arr1, arr2)))
print(np.hstack((arr1, arr2)))

[[ 5.  7.]
 [ 9. 11.]
 [ 2.  4.]
 [ 6.  8.]]
[[ 5.  7.  2.  4.]
 [ 9. 11.  6.  8.]]
